#!/usr/bin/env bash
#A Bash script that will display information about subdomains

if [ $# -eq 2 ]; then 
echo "The subdomain $2 is a \
$(dig "$2.$1" \
| grep "ANSWER SECTION" -A 1 \
| awk '/^'"$2.$1"'/ {getline; print $(NF-1)}') record of \
$(dig "$2.$1" \
| grep "ANSWER SECTION" -A 1 \
| awk '/^'"$2.$1"'/ {getline; print $NF}')"

elif [ $# -lt 2 ]; then
    my_subdomains=("www" "lb-01" "web-01" "web-02")
    for item in "${my_subdomains[@]}"; do
        echo "The subdomain $item is a $(dig "$item.$1" \
        | grep "ANSWER SECTION" -A 1\
        | awk '/^'"$item.$1"'/{getline; print $(NF-1)}') record and points to $(dig "$item.$1" \
        | grep "ANSWER SECTION" -A 1\
        | awk '/^'"$item.$1"'/{getline; print $NF}')"
    done

fi
