#!/bin/env bash

# Update package list
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Configure Nginx
sudo cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = / {
        return 200 "Hello World!";
    }
}
EOF

# Restart Nginx
sudo service nginx restart

