#!/usr/bin/env bash
# a Bash script that configures a server
grep -q "listen 80 default_server" /etc/nginx/sites-enabled/default || echo "Error: 'listen 80 default_server' is missing or misconfigured in /etc/nginx/sites-enabled/default"; sudo systemctl stop apache2; sudo nginx -t -c /etc/nginx/nginx.conf || echo "Error: Nginx is not run with sudo privileges"
