#!/usr/bin/env bash
# a Bash script that configures a server
awk '/^server {/,/^listen \[::\]:80 default_server;/ { if ($0 ~ /^ *listen [[:digit:]]+ default_server;/) print "        listen 80 default_server;"; else print; next } 1' /etc/nginx/sites-enabled/default > /tmp/default.tmp && sudo mv /tmp/default.tmp /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
kill "${pgrep 'nginx' | head -1}"
