#!/usr/bin/env bash
# Bash script that displays Best School 10 times
#   However, on the 9th iteration, displays "Hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
